// Generated by CoffeeScript 1.3.1
(function() {
  var Capkom, Stat, StopWatch, _ref;

  Capkom = (_ref = this.Capkom) != null ? _ref : this.Capkom = {};

  jQuery.widget("Capkom.wordmatch", {
    options: {
      profile: Capkom.profile,
      result: function(details) {
        return this.console.info('detailed results:', details);
      },
      symbolSize: 150,
      questions: [
        {
          type: 's2w',
          question: 'img/tree.jpg',
          choices: ['Baum', 'Haus', 'Hose'],
          correct: 'Baum'
        }, {
          type: 's2w',
          question: 'img/house.jpg',
          choices: ['Baum', 'Haus', 'Hose'],
          correct: 'Haus'
        }, {
          type: 's2w',
          question: 'img/pants.gif',
          choices: ['Baum', 'Haus', 'Hose'],
          correct: 'Hose'
        }, {
          type: 'w2s',
          question: 'Baum',
          choices: ['img/tree.jpg', 'img/pants.gif', 'img/house.jpg'],
          correct: 'img/tree.jpg'
        }, {
          type: 'w2s',
          question: 'Haus',
          choices: ['img/tree.jpg', 'img/pants.gif', 'img/house.jpg'],
          correct: 'img/house.jpg'
        }, {
          type: 'w2s',
          question: 'Hose',
          choices: ['img/tree.jpg', 'img/pants.gif', 'img/house.jpg'],
          correct: 'img/pants.gif'
        }
      ]
    },
    _create: function() {
      this._fixConsole();
      this.element.addClass('wordmatch-container');
      this.element.append("<div class='progressBar'></div>");
      this.progressBar = this.element.find(".progressBar");
      this.progressBar.css({
        'float': 'right',
        'width': '50%'
      });
      this.progressBar.progressbar();
      this.element.append("<div class='play-area'>\n  <table>\n    <tr><td><div class='question-area'></div></td></tr>\n    <tr><td><div class='answer-area'></div></td></tr>\n  </table>\n</div>");
      this.playArea = this.element.find('.play-area');
      this.questionArea = this.element.find('.question-area');
      this.answerArea = this.element.find('.answer-area');
      this.element.append("<div class='msg-dialog'></div>");
      this.messageArea = this.element.find('.msg-dialog');
      return this._beginGame();
    },
    _destroy: function() {
      this.element.html("");
      this.element.removeClass('wordmatch-container');
      return this.element.css({
        width: 'auto',
        height: 'auto'
      });
    },
    _beginGame: function() {
      this.sequence = this._shuffle(this.options.questions);
      this.results = {
        word2symbol: {
          correct: 0,
          wrong: 0,
          times: new Stat
        },
        symbol2word: {
          correct: 0,
          wrong: 0,
          times: new Stat
        }
      };
      this.timer = new StopWatch();
      return this._renderNext();
    },
    _renderNext: function() {
      var choice, _i, _j, _len, _len1, _ref1, _ref2,
        _this = this;
      if (!this.sequence.length) {
        this.finish();
      }
      this.question = this.sequence.shift();
      switch (this.question.type) {
        case 's2w':
          this.questionArea.html("<img class='question' src='" + this.question.question + "' width='" + (this.options.symbolSize * 2) + " height='" + (this.options.symbolSize * 2) + "'/>");
          this.answerArea.html('');
          _ref1 = this._shuffle(this.question.choices);
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            choice = _ref1[_i];
            this.answerArea.append("<button value='" + choice + "' width='" + this.options.symbolSize + " height='" + this.options.symbolSize + "'>" + choice + "</button>");
          }
          this.currentResultContainer = this.results.symbol2word;
          break;
        case 'w2s':
          this.questionArea.html("<h1>" + this.question.question + "</h1>");
          this.answerArea.html('');
          _ref2 = this._shuffle(this.question.choices);
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            choice = _ref2[_j];
            this.answerArea.append("<button value='" + choice + "' width='" + this.options.symbolSize + " height='" + this.options.symbolSize + "'>\n  <img class='choice' src='" + choice + "' width='" + this.options.symbolSize + " height='" + this.options.symbolSize + "'/>\n</button>");
          }
          this.currentResultContainer = this.results.word2symbol;
      }
      this.buttonsDisabled = false;
      this.playArea.find('button').button().css({
        minWidth: this.options.symbolSize,
        minHeight: this.options.symbolSize
      }).click(function(e) {
        var attempt;
        if (!_this.buttonsDisabled) {
          _this.buttonsDisabled = true;
          attempt = jQuery(e.currentTarget).attr('value');
          if (attempt === _this.question.correct) {
            _this.currentResultContainer.times.add(_this.timer.end());
            _this.currentResultContainer.correct++;
            jQuery(e.currentTarget).css({
              'border': 'lightgreen 5px solid'
            });
            return _this.message('Korrekt!', function() {
              _this.buttonsDisabled = false;
              return _this._renderNext();
            });
          } else {
            _this.currentResultContainer.wrong++;
            jQuery(e.currentTarget).css({
              'border': 'red 5px solid'
            });
            return _this.message("Leider falsch.. Versuch's noch einmal!", function() {
              _this.buttonsDisabled = false;
              return jQuery(e.currentTarget).css({
                'border': ''
              });
            });
          }
        }
      });
      return this.timer.start();
    },
    message: function(msg, cb) {
      var afterWaiting,
        _this = this;
      this.messageArea.html(msg).dialog();
      afterWaiting = function() {
        _this.messageArea.dialog('destroy');
        return cb();
      };
      return setTimeout(afterWaiting, 100);
    },
    finish: function() {
      this.playArea.html('');
      this.results.word2symbol.score = this.results.word2symbol.correct / (this.results.word2symbol.correct + this.results.word2symbol.wrong);
      this.results.word2symbol.times = this.results.word2symbol.times.getStatistics();
      this.results.symbol2word.score = this.results.symbol2word.correct / (this.results.symbol2word.correct + this.results.symbol2word.wrong);
      this.results.symbol2word.times = this.results.symbol2word.times.getStatistics();
      console.info('results', this.results);
      return jQuery('.results').html(JSON.stringify(this.results));
    },
    getInnerWidth: function() {
      return jQuery(window).width();
      if (jQuery.browser.msie) {
        return screen.availWidth;
      } else {
        return window.innerWidth;
      }
    },
    getInnerHeight: function() {
      return jQuery(window).height();
      if (jQuery.browser.msie) {
        return screen.availHeight;
      } else {
        return window.innerHeight;
      }
    },
    _fixConsole: function() {
      if (window.console) {
        return this.console = console;
      } else {
        return this.console = {
          info: function() {},
          error: function() {},
          log: function() {}
        };
      }
    },
    _shuffle: function(arr) {
      var randOrd;
      randOrd = function() {
        return Math.round(Math.random()) - 0.5;
      };
      return arr.splice(0).sort(randOrd);
    }
  });

  Stat = (function() {

    Stat.name = 'Stat';

    function Stat(opts) {
      var options;
      options = {
        dropMargins: true
      };
      this.options = _.extend(options, opts);
      this._values = [];
    }

    Stat.prototype.getSamples = function() {
      var res;
      if (this.options.dropMargins) {
        res = _.sortBy(this._values, function(v) {
          return v;
        });
        return res.slice(1, -1);
      } else {
        return this._values;
      }
    };

    Stat.prototype.add = function(val) {
      return this._values.push(val);
    };

    Stat.prototype.length = function() {
      return this._values.length;
    };

    Stat.prototype.clear = function() {
      return this._values = [];
    };

    Stat.prototype.getAverage = function() {
      var smpls, sum;
      sum = 0;
      smpls = this.getSamples();
      _.each(smpls, function(val) {
        return sum += val;
      });
      return sum / smpls.length;
    };

    Stat.prototype.getVariance = function() {
      var av, smpls, v;
      av = this.getAverage();
      smpls = this.getSamples();
      v = 0;
      _.each(smpls, function(val) {
        return v += (av - val) * (av - val);
      });
      return v = v / smpls.length;
    };

    Stat.prototype.getStandardDeviation = function() {
      return Math.sqrt(this.getVariance());
    };

    Stat.prototype.getStatistics = function() {
      return {
        average: this.getAverage(),
        variance: this.getVariance(),
        standardDeviation: this.getStandardDeviation()
      };
    };

    return Stat;

  })();

  StopWatch = (function() {

    StopWatch.name = 'StopWatch';

    function StopWatch(error) {
      this.error = error != null ? error : function() {
        return this.console.error.apply(this.console, arguments);
      };
      this.elapsed = 0;
      this.status = 'idle';
    }

    StopWatch.prototype.start = function() {
      if (this.status === 'idle') {
        this.startTime = new Date().getTime();
        return this.status = 'running';
      } else {
        return this.error("Already running!");
      }
    };

    StopWatch.prototype.stop = function() {
      if (this.status === 'running') {
        this.elapsed += new Date().getTime() - this.startTime;
        return this.status = 'idle';
      } else {
        return this.error("Stop watch is not running, cannot stop!");
      }
    };

    StopWatch.prototype.clear = function() {
      this.elapsed = 0;
      return this.status = 'idle';
    };

    StopWatch.prototype.isRunning = function() {
      return this.status === 'running';
    };

    StopWatch.prototype.end = function() {
      var res;
      this.stop();
      res = this.elapsed;
      this.clear();
      return res;
    };

    StopWatch.prototype.clearAndStart = function() {
      this.clear();
      return this.start();
    };

    return StopWatch;

  })();

}).call(this);
