// Generated by CoffeeScript 1.3.1
(function() {
  var Capkom, _ref;

  Capkom = (_ref = this.Capkom) != null ? _ref : this.Capkom = {};

  jQuery.widget("Capkom.explain", {
    options: {
      profile: Capkom.profile,
      read: "This will be heard",
      html: "This will be shown. <button>Testknopf</button>",
      useAudio: true,
      domInit: function(element, done) {
        jQuery(element).find('button').button();
        return done();
      },
      after: function() {
        return alert("this should happen after reading the text.");
      },
      ttsOptions: {},
      maxSize: 200,
      minSize: 100,
      clickCount: 5,
      result: function(bestSize, details) {
        var res, result, size;
        res = "<h2>Results</h2>";
        res += "Measured Sizes (these sizes depend from the screen size)";
        res += "<ul>";
        for (size in details) {
          result = details[size];
          res += "<li>\n  size: " + size + "px, score: " + (Math.round(result.score * 100)) + " %<br/>\n  Reaction time: average: " + result.reactionTimeAverage + ", standard deviation: " + result.reactionTimeStDev + "<br/>\n  Move time: average: " + result.moveTimeAverage + ", standard deviation: " + result.moveTimeStDev + "\n </li>";
        }
        res += "</ul>";
        res += "<p>Minimum size resulted in " + bestSize + "</p>";
        jQuery('#results').html(res);
        return this.console.info('ideal size:', size, 'detailed results:', details);
      }
    },
    _create: function() {
      var _this = this;
      this.element.html("<div tts=\"" + this.options.read + "\" class=\"explain\">" + this.options.html + "</div>");
      this.explainPanel = this.element.find('.explain');
      return this.options.domInit(this.explainPanel, function() {
        var options;
        options = _.extend(_this.options.ttsOptions, {
          mode: 'auto',
          beforeDialog: function() {
            return _this.explainPanel.ttswidget('getInnerContentElement', function(innerContent) {
              console.info(_this.explainPanel, innerContent);
              return innerContent.append(_this.explainPanel);
            });
          },
          done: function() {
            _this._trigger('after');
            return _.defer(function() {
              if (_this.explainPanel) {
                _this.explainPanel.remove();
                return _this.explainPanel = null;
              }
            });
          },
          forcedClose: function() {
            return _this._trigger('forcedClose');
          }
        });
        return _this.explainPanel.ttswidget(options);
      });
    },
    _destroy: function() {
      return this.element.append(this.explainPanel);
    }
  });

}).call(this);
